### ISSUE TITLE
Planning to remove this repo

### ISSUE THREAD

**Issue by alistair-RG** [boxfuse/boxfuse.com#2]
Hi there,
This doesn't appear to be doing anything anymore so we'd like to remove it from the flyway org.
Any objections then let me know by Friday  23rd Feb 2024

**Comment by axelfontaine** [comment]
@alistair-RG This repo provides a redirect from boxfuse.com to cloudcaptain.sh through GitHub Pages. Please leave it in place if it doesn't cause you any trouble.

**Comment by alistair-RG** [comment]
OK - we'll leave it be for now, the issue is around 'who can update repo' and I think in this case it is us - I'll look at a protected branch for the repo if it doesn't have it already
